services:
  _defaults:
    public: true

  darkside.dsgooglereviews.form.ds_google_reviews_text_type:
    class: 'DarkSide\DsGoogleReview\Form\DsGoogleReviewsTextType'
    parent: 'form.type.translatable.aware'
    public: true
    tags:
      - { name: form.type }

  darkside.dsgooglereviews.form.ds_google_reviews_text_form_data_provider:
    class: 'DarkSide\DsGoogleReview\Form\DsGoogleReviewsDataProvider'
    arguments:
      - '@darkside.dsgooglereviews.form.ds_google_reviews_text_data_configuration'

  darkside.dsgooglereviews.form.ds_google_reviews_text_form_data_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\Handler'
    arguments:
      - '@form.factory'
      - '@prestashop.core.hook.dispatcher'
      - '@darkside.dsgooglereviews.form.ds_google_reviews_text_form_data_provider'
      - 'DarkSide\DsGoogleReview\Form\DsGoogleReviewsTextType'
      - '@darkside.dsgooglereviews.controller.ds_google_reviews_controller'

  darkside.dsgooglereviews.form.ds_google_reviews_text_data_configuration:
    class: DarkSide\DsGoogleReview\Form\DsGoogleReviewsConfiguration
    arguments: ['@prestashop.adapter.legacy.configuration']

  darkside.dsgooglereviews.controller.ds_google_reviews_controller: 
    class: DarkSide\DsGoogleReview\Controller\DsGoogleReviewsController
    arguments:
      - '@darkside.dsgooglereviews.service.ds_google_reviews_service'
    tags:
        - { name: 'controller.service_arguments' }

  darkside.dsgooglereviews.service.ds_google_reviews_service:
    class: DarkSide\DsGoogleReview\Service\DsGoogleReviewService
  